
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - docker-compose-local.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - docker-compose-local.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  db_migrate:
    image: transact-api-migrate
    build:
      context: .
      dockerfile: infrastructure/Migrate.Dockerfile
    depends_on:
      - db
    env_file:
      - docker-compose-local.env
    volumes:
      - db-data:/db-data
    command: ["/bin/sh", "-c", "/migrate/wait-for-db.sh -- /migrate/db-migration.sh"]

  transact_api:
    image: transact_api
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    depends_on:
      - db_migrate
    env_file:
      - docker-compose-local.env
    ports:
      - "8080:8080"
    command: ["/bin/sh", "-c", "/app/wait-for-db.sh -- /app/transact-api"]
volumes:
  pgdata:
  pgadmin-data:
  db-data:
